import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import type { Alert, BloodRequest, Hospital, Inventory, Log, Store } from "./types";

const dataPath = join(process.cwd(), "data", "store.json");
const seedPath = join(process.cwd(), "data", "sample-store.json");
async function ensureStore() { if (!existsSync(dataPath)) { await mkdir(join(process.cwd(), "data"), { recursive:true }); await copyFile(seedPath, dataPath); } }
export async function getStore(): Promise<Store> { await ensureStore(); return JSON.parse(await readFile(dataPath, "utf8")) as Store; }
export async function saveStore(store: Store) { await writeFile(dataPath, JSON.stringify(store, null, 2), "utf8"); }
export function hospital(store:Store, id?:string): Hospital | undefined { return store.hospitals.find(h=>h.id===id); }
export function inventoryFor(store:Store, hospitalId?:string) { return store.inventory.filter(i=>i.hospitalId===hospitalId); }
export function available(i:Inventory) { return Math.max(0, i.quantity - i.reserved); }
export function displayTime(iso:string) { const mins=Math.max(0, Math.round((Date.now()-new Date(iso).getTime())/60000)); if(mins<2)return "Updated just now"; if(mins<60)return `Updated ${mins} minutes ago`; const hours=Math.floor(mins/60); if(hours<24)return `Last updated ${hours} hour${hours===1?"":"s"} ago`; return `Updated ${new Date(iso).toLocaleDateString()}`; }
export function requestName(store:Store, r:BloodRequest, supplying=false) { return hospital(store, supplying ? r.supplyingHospitalId : r.requestingHospitalId)?.name ?? "Not assigned"; }
export function addLog(store:Store, action:string, detail:string, fields:Partial<Log>={}) { store.logs.unshift({id:`LOG-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,action,detail,createdAt:new Date().toISOString(),...fields}); }
export async function createRequest(input: Omit<BloodRequest,"id"|"status"|"createdAt"|"updatedAt">, userId:string) {
 const store=await getStore(); const now=new Date().toISOString(); const id=`REQ-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${String(store.requests.length+1).padStart(3,"0")}`;
 const request:BloodRequest={...input,id,status:"PENDING",createdAt:now,updatedAt:now}; store.requests.unshift(request);
 for(const i of store.inventory) if(i.hospitalId!==input.requestingHospitalId && available(i)>=input.quantity && i.bloodGroup===input.bloodGroup && hospital(store,i.hospitalId)?.active) store.alerts.unshift({id:`AL-${Date.now()}-${i.id}`,hospitalId:i.hospitalId,requestId:id,read:false,createdAt:now});
 addLog(store,"Emergency request created",`${input.bloodGroup} / ${input.quantity} units requested.`,{hospitalId:input.requestingHospitalId,userId,objectId:id}); await saveStore(store); return {request, matches:store.alerts.filter(a=>a.requestId===id).length};
}
export async function respondToRequest(requestId:string, supplyingHospitalId:string, userId:string, accept:boolean) {
 const store=await getStore(); const request=store.requests.find(r=>r.id===requestId); if(!request || request.status!=="PENDING") return {ok:false,message:"This request is no longer pending."};
 if(!accept){ const alert=store.alerts.find(a=>a.requestId===requestId&&a.hospitalId===supplyingHospitalId); if(alert) alert.read=true; addLog(store,"Request marked unavailable","Receiving hospital reported unavailable inventory.",{hospitalId:supplyingHospitalId,userId,objectId:requestId}); await saveStore(store); return {ok:true,message:"Request marked unavailable for your hospital."}; }
 const item=store.inventory.find(i=>i.hospitalId===supplyingHospitalId&&i.bloodGroup===request.bloodGroup); if(!item || available(item)<request.quantity) return {ok:false,message:"Insufficient reported inventory to reserve this request."};
 item.reserved+=request.quantity; item.updatedAt=new Date().toISOString(); request.status="ACCEPTED"; request.supplyingHospitalId=supplyingHospitalId; request.updatedAt=new Date().toISOString(); store.alerts.forEach(a=>{if(a.requestId===requestId)a.read=true}); addLog(store,"Request accepted",`${request.quantity} ${request.bloodGroup} units reserved.`,{hospitalId:supplyingHospitalId,userId,objectId:requestId}); await saveStore(store); return {ok:true,message:"Request accepted and inventory reserved."};
}
export async function completeRequest(requestId:string, hospitalId:string, userId:string) { const store=await getStore(); const r=store.requests.find(x=>x.id===requestId); if(!r||r.status!=="ACCEPTED"||r.supplyingHospitalId!==hospitalId) return {ok:false,message:"This request cannot be completed."}; const item=store.inventory.find(i=>i.hospitalId===hospitalId&&i.bloodGroup===r.bloodGroup); if(!item || item.reserved<r.quantity || item.quantity<r.quantity) return {ok:false,message:"Inventory reservation could not be verified."}; item.reserved-=r.quantity; item.quantity-=r.quantity; item.updatedAt=new Date().toISOString(); r.status="COMPLETED";r.updatedAt=new Date().toISOString();addLog(store,"Request marked completed",`${r.quantity} ${r.bloodGroup} units used from reserved inventory.`,{hospitalId,userId,objectId:r.id});await saveStore(store);return {ok:true,message:"Request completed and inventory recorded."}; }
export async function updateInventory(hospitalId:string,bloodGroup:Inventory["bloodGroup"],quantity:number,userId:string){const store=await getStore();if(!Number.isInteger(quantity)||quantity<0)return {ok:false,message:"Quantity must be a non-negative whole number."};let item=store.inventory.find(i=>i.hospitalId===hospitalId&&i.bloodGroup===bloodGroup);if(item&&quantity<item.reserved)return {ok:false,message:`Quantity cannot be lower than ${item.reserved} reserved unit(s).`};const old=item?.quantity??0;if(item){item.quantity=quantity;item.updatedAt=new Date().toISOString()}else{item={id:`INV-${Date.now()}`,hospitalId,bloodGroup,quantity,reserved:0,updatedAt:new Date().toISOString()};store.inventory.push(item)}addLog(store,"Inventory updated",`${bloodGroup}: ${old} to ${quantity} reported units.`,{hospitalId,userId,objectId:item.id});await saveStore(store);return {ok:true,message:"Inventory updated."}}
export async function markAlertsRead(hospitalId:string){const store=await getStore();store.alerts.forEach(a=>{if(a.hospitalId===hospitalId)a.read=true});await saveStore(store)}
